name: Deploy
on: [push, pull_request]
# on:
#   workflow_run:
#     branches: [main]
#     workflows: [Integration]
#     types: [completed]

jobs:
  release:
    defaults:
      run:
        working-directory: news

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo run

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
